# Generated by Django 4.2.2 on 2023-07-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_item_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
